export const flexSliderCardConfigLabels: Record<string, string> = {
  name: "Name",
  format: "Format",
  valuesbaractive: "Enable values bar",
  bubblesactive: "Enable bubbles",
  entity_min: "Entity for minimum",
  entity_max: "Entity for maximum",
  min: "Min (Number only)",
  max: "Max (Number only)",
  step: "Step (Number only)",
  unit: "Unit", 
  digits: "Digits Mode",
  nbdigits: "Number of Digits (Manual only)",
  mintext: "Text for min value",
  maxtext: "Text for max value",
  dragonly: "Visible during drag only",
  direction: "Direction",
  orientation: "Orientation",
  horizontalwidth: "Slider width (%)",
  verticalheight: "Slider height (rows)",
  ticksactive: "Show tick marks",
  majorticks: "Number of Major Ticks",
  minorticks: "Number of Minor Ticks",
};