export const flexSliderCardConfigLabels: Record<string, string> = {
  name: "Name",
  format: "Format",
  valuesbaractive: "Enable values bar",
  bubblesactive: "Enable bubbles",
  referenceactive: "Enable reference entity",
  adaptivestateactive: "Enable Adaptative State",
  conditions: "External condition",
  editablewhenlinkedinactive: "Editable when linked inactive state",
  entity: "Entity",
  text: "Text",
  bubble: "Show bubble",
  connectprevious: "Connect with previous",
  connectend: "Connect at end",
  min: "Min (Number only)",
  max: "Max (Number only)",
  step: "Step (Number only)",
  handlesbehavior: "Handle behavior",
  unit: "Unit", 
  valuesbar: "Show values bar",
  valuesbartextlarge: "Values bar large text",
  showtext: "Show text",
  digits: "Digits Mode",
  nbdigits: "Number of Digits (Manual only)",
  dragonly: "Visible during drag only",
  direction: "Direction",
  orientation: "Orientation",
  verticallayout: "Vertical layout",
  horizontalwidth: "Slider width (%)",
  verticalheight: "Slider height (rows)",
  ticksactive: "Show tick marks",
  majorticks: "Number of Major Ticks",
  minorticks: "Number of Minor Ticks",
  reference: "Reference entity",
};
